language: bash
dist: bionic

env:
  global:
    - DOCKER_REPO=nginx-proxy
branches:
  only:
    - master
before_install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
  - docker version
  - docker info
  # prepare docker test requirements
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use
script:
  - bash ci.sh
